name: Rust

on:
  push:
    branches: [ primary ]
  pull_request:
    branches: [ primary ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Switch To Beta
      run: rustup default beta
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
